name: my-drizzle

services:
  mysql:
    image: mysql:9.7.2-oraclelinux9
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']
    networks:
      - gateway-database
      - workbench-database

  drizzle-gateway:
    build: ./drizzle
    pull_policy: build
    profiles:
      - drizzle
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_URL: mysql://root:password@mysql:3306/app
    volumes:
      - type: volume
        source: drizzle-gateway-data
        target: /app
    ports:
      - target: 4983
        published: '4983'
        host_ip: 127.0.0.1
        protocol: tcp
    networks:
      - gateway-database

  mysql-workbench:
    build: ./workbench
    pull_policy: build
    profiles:
      - workbench
    depends_on:
      mysql:
        condition: service_healthy
    cap_add:
      - IPC_LOCK
    environment:
      START_DOCKER: 'false'
      HARDEN_DESKTOP: 'true'
      HARDEN_OPENBOX: 'true'
    volumes:
      - type: volume
        source: mysql-workbench-data
        target: /config
    ports:
      - target: 3001
        published: '3001'
        host_ip: 127.0.0.1
        protocol: tcp
    shm_size: 1gb
    networks:
      - workbench-database

networks:
  gateway-database:
  workbench-database:

volumes:
  mysql-data:
  drizzle-gateway-data:
  mysql-workbench-data:
